/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    DateInputPicker: typeof import('./components/DateInputPicker.vue')['default']
    FormItem: typeof import('./components/FormItem.vue')['default']
    Header: typeof import('./components/header.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    MoneyInputWithLabel: typeof import('./components/shared/MoneyInputWithLabel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SessionItem: typeof import('./components/badmintonSession/SessionItem.vue')['default']
    StatusTag: typeof import('./components/shared/StatusTag.vue')['default']
    TextAreaWithLabel: typeof import('./components/TextAreaWithLabel.vue')['default']
    TextFieldMoney: typeof import('./components/TextFieldMoney.vue')['default']
    TextFieldWithLabel: typeof import('./components/TextFieldWithLabel.vue')['default']
  }
}
