/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/BadmintonSession': RouteRecordInfo<'/BadmintonSession', '/BadmintonSession', Record<never, never>, Record<never, never>>,
    '/BadmintonSessionDetail': RouteRecordInfo<'/BadmintonSessionDetail', '/BadmintonSessionDetail', Record<never, never>, Record<never, never>>,
    '/ChangePasswordPage': RouteRecordInfo<'/ChangePasswordPage', '/ChangePasswordPage', Record<never, never>, Record<never, never>>,
    '/HomePage': RouteRecordInfo<'/HomePage', '/HomePage', Record<never, never>, Record<never, never>>,
    '/LoginPage': RouteRecordInfo<'/LoginPage', '/LoginPage', Record<never, never>, Record<never, never>>,
    '/LogoutPage': RouteRecordInfo<'/LogoutPage', '/LogoutPage', Record<never, never>, Record<never, never>>,
    '/NotFoundPage': RouteRecordInfo<'/NotFoundPage', '/NotFoundPage', Record<never, never>, Record<never, never>>,
    '/PaymentList': RouteRecordInfo<'/PaymentList', '/PaymentList', Record<never, never>, Record<never, never>>,
    '/PolicyPage': RouteRecordInfo<'/PolicyPage', '/PolicyPage', Record<never, never>, Record<never, never>>,
    '/RegisterPage': RouteRecordInfo<'/RegisterPage', '/RegisterPage', Record<never, never>, Record<never, never>>,
    '/TransactionHistory': RouteRecordInfo<'/TransactionHistory', '/TransactionHistory', Record<never, never>, Record<never, never>>,
    '/UserManagement': RouteRecordInfo<'/UserManagement', '/UserManagement', Record<never, never>, Record<never, never>>,
  }
}
